<?php
namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AmfsSeeder extends Seeder
{
    public function run()
    {

        // --- DONNÉES BRUTES ET NETTOYAGE ---
        $data = [];

        // Données d'origine de l'exportation phpMyAdmin, formatées ici pour le traitement:
        $amfsRawData = array(
          array('user' => '1','nom' => '28 ans plus tard','categorie' => '8','lien' => 'https://uqload.cx/chhmlqktcehh.html','description' => 'Temps : 21\'56','image' => 'https://tse4.mm.bing.net/th/id/OIP.NRRxGGIO7vWD0LLDhYGApQHaE7?pid=Api&P=0&h=180','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => '28 Jours plus tard','categorie' => '8','lien' => 'https://nightflix{ext}/film/28-jours-plus-tard','description' => 'Temps : 1h15','image' => 'https://summury.22web.org/banqueimage/img/amfs/films/28-j-plus-tard.webp','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'American Nightmare 2','categorie' => '8','lien' => 'https://nightflix{ext}/film/american-nightmare-2','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/americannightmare2.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'American Nightmare 3','categorie' => '8','lien' => 'https://nightflix{ext}/film/american-nightmare-3-Elections','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/americannightmare3.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'American Nightmare 4','categorie' => '8','lien' => 'https://nightflix{ext}/film/american-nightmare-4-les-origines','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/americannightmare4.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'American Nightmare 5','categorie' => '8','lien' => 'https://nightflix{ext}/film/american-nightmare-5-sans-limites','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/americannightmare5.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Anime Sama','categorie' => '3','lien' => 'https://anime-sama.fr/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/anime_sama.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'a playthrough of a certain dudes','categorie' => '10','lien' => 'https://v6.voiranime.com/anime/a-playthrough-of-a-certain-dudes-vrmmo-life/a-playthrough-of-a-certain-dudes-vrmmo-life-01-vostfr/','description' => NULL,'image' => 'https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/44479557b36fceda01ee2977142fc5dd.jpg','dateLimite' => '2006-07-02T00:00','saison' => '1/1','episode' => '6/12'),
          array('user' => '1','nom' => 'Arrete moi si tu peux','categorie' => '8','lien' => 'https://nightflix{ext}/film/arrete-moi-si-tu-peux','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/arrete-moi-si-tu-peux.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Audio To Text','categorie' => '5','lien' => 'https://editor.flixier.com/transcribe?fx_source=search&lang=en&fx_campaign=convert-audio-to-text&fx_medium=tools','description' => 'Convertir les fichiers audio en textes','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/audio_to_text.gif','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Avatar 2','categorie' => '8','lien' => 'https://nightflix{ext}/film/avatar-2','description' => NULL,'image' => 'https://freakingeek.com/wp-content/uploads/2022/12/Avatar2-Banniere-800x445.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'B: The Beginning','categorie' => '11','lien' => 'https://anime-sama.fr/catalogue/b-the-beginning/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/b-the-beginning.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Bad Boys 1','categorie' => '8','lien' => 'https://nightflix{ext}/film/bad-boys','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/bad-boys-1.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Bad Boys 2','categorie' => '8','lien' => 'https://nightflix{ext}/film/bad-boys-2','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/bad-boys-2.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Bad Boys 3','categorie' => '8','lien' => 'https://nightflix{ext}/film/bad-boys-3','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/bad-boys-3.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Bad Boys: Ride or die','categorie' => '8','lien' => 'https://nightflix{ext}/film/bad-boys-ride-or-die','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/bad-boys-4.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Bananime','categorie' => '3','lien' => 'https://bananimes.com/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/bananime.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Berserk','categorie' => '14','lien' => 'https://sushiscan.net/berserk-volume','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/berserk.jpg','dateLimite' => '2024-03-23T00:00','saison' => '1/1','episode' => '10/1'),
          array('user' => '1','nom' => 'Black Clover','categorie' => '14','lien' => 'https://sushiscan.fr/black-clover-chapitre-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/black-clover.jpg','dateLimite' => '2024-01-02T18:30:00.000Z','saison' => '1/1','episode' => '378/0'),
          array('user' => '1','nom' => 'Bleach','categorie' => '12','lien' => 'https://v5.voiranime.com/anime/bleach/bleach-','description' => '( 2 saisons )','image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/bleach.jpg','dateLimite' => '2020-05-25T07:00','saison' => '1/1','episode' => '210/366'),
          array('user' => '1','nom' => 'Blue Exorcist','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/ao-no-exorcist-3-shimane-illuminati-hen/ao-no-exorcist-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/blue-exorcist.jpg','dateLimite' => '2024-01-13T18:30:00.000Z','saison' => '3/3','episode' => '11/12'),
          array('user' => '1','nom' => 'bootstrap icons','categorie' => '5','lien' => 'https://icons.getbootstrap.com','description' => 'Bibliothèque d\'icônes','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/bootstrap-icons.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Boruto','categorie' => '12','lien' => 'https://v5.voiranime.com/anime/boruto-naruto-next-generations/boruto-naruto-next-generations-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/boruto.jpg','dateLimite' => '2020-05-25T11:00:00.000Z','saison' => '1/1','episode' => '110/293'),
          array('user' => '1','nom' => 'Blue Period','categorie' => '12','lien' => 'https://v5.voiranime.com/anime/blue-period/blue-period-12-vostfr/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/blue-period.jpg','dateLimite' => '2020-05-25T11:00:00.000Z','saison' => '1/1','episode' => '12/12'),
          array('user' => '1','nom' => 'Canal + FOOT','categorie' => '1','lien' => 'https://nightflix{ext}/tv/?play=canal-footx','description' => NULL,'image' => 'https://alloforfait.fr/wp-content/uploads/2022/09/canal-foot-300x200.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'a certain scientific accelerator','categorie' => '11','lien' => 'https://anime-sama.fr/catalogue/a-certain-scientific-accelerator/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/a-certain-scientific-accelerator.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Classroom of the Elite','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/classroom-of-the-elite-3/classroom-of-the-elite-3-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/classroom-of-the-elite.jpg','dateLimite' => '2024-01-04T18:00:00.000Z','saison' => '3/3','episode' => '10/13'),
          array('user' => '1','nom' => 'Cleanup','categorie' => '5','lien' => 'https://cleanup.pictures/','description' => 'Nettoyer des images','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/cleanup.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Copilot','categorie' => '5','lien' => 'https://www.bing.com/chat?q=Microsoft+Copilot&FORM=hpcodx','description' => 'Résoudre n\'importe quoi','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/copilot.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'À la croisée des mondes','categorie' => '6','lien' => 'https://papadustream{ext}/cat-series/drame-s/2865-his-dark-materials-a-la-croisee-des-mondes-30c/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/croisee_des_mondes.png','dateLimite' => '2019-06-20T04:00','saison' => '1/3','episode' => '1/8'),
          array('user' => '1','nom' => 'DALL.E','categorie' => '5','lien' => 'https://labs.openai.com/','description' => 'Générer des Images','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/dall_e.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Dandadan','categorie' => '14','lien' => 'https://www.lelmanga.com/dandadan-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/dandadan.jpg','dateLimite' => '2023-03-31T23:00:00.000Z','saison' => '1/1','episode' => '89/0'),
          array('user' => '1','nom' => 'Dandadan','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/dandadan/dandadan-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/dandadan.jpg','dateLimite' => '2024-10-15T13:38','saison' => '1/1','episode' => '10/12'),
          array('user' => '1','nom' => 'Dragon Ball','categorie' => '14','lien' => 'https://v5.voiranime.com/anime/dragon-ball/dragon-ball-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/dragon-ball.jpg','dateLimite' => '2020-05-25T11:00:00.000Z','saison' => '1/1','episode' => '10/153'),
          array('user' => '1','nom' => 'demon slayer','categorie' => '14','lien' => 'https://anime-sama.fr/catalogue/demon-slayer/scan/vf/','description' => 'Dernier lu: 125','image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/demon-slayer.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Divergeante 2','categorie' => '8','lien' => 'https://nightflix{ext}/film/divergente-2','description' => 'temps: 01:04:16','image' => 'https://summury.22web.org/banqueimage/img/amfs/films/divergente-2.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Divergeante 3','categorie' => '8','lien' => 'https://nightflix{ext}/film/divergente-3','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/divergente-3.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'dr stone','categorie' => '14','lien' => 'https://anime-sama.fr/catalogue/dr-stone/scan/vf/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/dr-stone.jpg','dateLimite' => '2025-10-14','saison' => '1/1','episode' => '116/1'),
          array('user' => '1','nom' => 'Durable','categorie' => '5','lien' => 'https://app.durable.co/dashboard','description' => 'Générer de site web','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/durable.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Fotor','categorie' => '5','lien' => 'https://www.fotor.com/','description' => 'conceptions et éditions d\'images','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/fotor.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Gladiator 2','categorie' => '8','lien' => 'https://nightflix{ext}/film/gladiator-2','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/gladiator2.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Goblin Slayer','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/goblin-slayer-ii/goblin-slayer-2-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/goblin-slayer.jpg','dateLimite' => '2020-05-25T07:00','saison' => '2/2','episode' => '11/12'),
          array('user' => '1','nom' => 'Game of Throne : House of the Dragon','categorie' => '6','lien' => 'https://papadustream{ext}/categorie-series/drame-s/10697-game-of-thrones-house-of-the-dragon/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/got-hd.png','dateLimite' => '2023-12-20','saison' => '1/3','episode' => '1/10'),
          array('user' => '1','nom' => 'Chat GPT','categorie' => '5','lien' => 'https://chat.openai.com/','description' => 'Résoudre n\'importe quoi','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/gpt.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'hells paradise','categorie' => '14','lien' => 'https://anime-sama.fr/catalogue/hells-paradise/scan/vf/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/hells-paradise.jpg','dateLimite' => '2025-10-14','saison' => '1/1','episode' => '47/1'),
          array('user' => '1','nom' => 'the hidden dungeon','categorie' => '11','lien' => 'https://anime-sama.fr/catalogue/the-hidden-dungeon/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/the-hidden-dungeon.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'In Another World with my Smartphone','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/isekai-wa-smartphone-to-tomo-ni/isekai-wa-smartphone-to-tomo-ni-','description' => '( 2 saisons )','image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/in-another-world-with-my-smartphone.jpg','dateLimite' => '2020-05-25T11:00:00.000Z','saison' => '1/1','episode' => '10/12'),
          array('user' => '1','nom' => 'jagaaan','categorie' => '11','lien' => 'https://anime-sama.fr/catalogue/jagaaan/scan/vf/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/jagaaan.jpg','dateLimite' => '2025-10-14','saison' => '1/1','episode' => '36/1'),
          array('user' => '1','nom' => 'Jujutsu Kaisen','categorie' => '14','lien' => 'https://sushiscan.fr/jujutsu-kaisen-chapitre-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/jujutsu-kaisen.jpg','dateLimite' => '2024-03-23T23:00:00.000Z','saison' => '1/1','episode' => '148/0'),
          array('user' => '1','nom' => 'Kaiju n°8','categorie' => '14','lien' => 'https://www.lelmanga.com/kaiju-no-8-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/kaiju-n8.jpg','dateLimite' => '2023-09-07T17:15:00.000Z','saison' => '1/1','episode' => '102/0'),
          array('user' => '1','nom' => 'Kaiju n°8','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/kaiju-no-8/kaiju-no-8-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/kaiju-n8.jpg','dateLimite' => '2024-05-04','saison' => '1/1','episode' => '1/12'),
          array('user' => '1','nom' => 'Konosuba','categorie' => '11','lien' => 'https://anime-sama.fr/catalogue/konosuba/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/konosuba.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Krea.ai','categorie' => '5','lien' => 'https://www.krea.ai/apps/image/realtime','description' => 'Générer des Images','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/kreaai.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'lelmanga','categorie' => '4','lien' => 'https://www.lelmanga.com/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/lelmanga.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Les misérables','categorie' => '8','lien' => 'https://nightflix{ext}/film/les-miserables','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/les-miserables.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Planète des singes : L\'affrontement','categorie' => '8','lien' => 'https://nightflix{ext}/film/la-planete-des-singes-l-affrontement','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/lpds-2.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Planète des singes : Suprématie','categorie' => '8','lien' => 'https://nightflix{ext}/film/la-planete-des-singes-suprematie','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/lpds-3.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Planète des singes : Le Nouveau Royaume','categorie' => '8','lien' => 'https://nightflix{ext}/film/la-planete-des-singes-le-nouveau-royaume','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/lpds-4.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Mashle','categorie' => '14','lien' => 'https://anime-sama.fr/catalogue/mashle/scan/vf/','description' => 'Dernier lu: 38','image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/mashle.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'My hero Academia','categorie' => '10','lien' => 'https://v6.voiranime.com/anime/boku-no-hero-academia-8/boku-no-hero-academia-8','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/my-hero-academia.jpg','dateLimite' => '2025-12-13T09:00','saison' => '8/8','episode' => '11/11'),
          array('user' => '1','nom' => 'Murim Login','categorie' => '13','lien' => 'https://legacy-scans.com/manga/murim-login/chapter/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/scan/murim-login.png','dateLimite' => '2024-03-23T19:00','saison' => '1/1','episode' => '75/1'),
          array('user' => '1','nom' => 'Netflix','categorie' => '1','lien' => 'https://www.netflix.com/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/netflix.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'NightFlix','categorie' => '1','lien' => 'https://nightflix.stream/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/nightflix.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'obfuscator','categorie' => '5','lien' => 'https://obfuscator.io/','description' => 'crypter les scripts javascripts','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/obfuscator.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'One punch man','categorie' => '10','lien' => 'https://v6.voiranime.com/anime/one-punch-man-3/one-punch-man-3','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/one-punch-man.jpg','dateLimite' => '2025-11-16T23:59','saison' => '3/3','episode' => '6/12'),
          array('user' => '1','nom' => 'Animé : One Piece','categorie' => '10','lien' => 'https://v6.voiranime.com/anime/one-piece/one-piece-0001-vostfr/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/one-piece.jpg','dateLimite' => '2024-05-03T00:00','saison' => '1/1','episode' => '1141/1'),
          array('user' => '1','nom' => 'Manga : One piece','categorie' => '13','lien' => 'https://www.scan-vf.net/one_piece/chapitre-1','description' => NULL,'image' => 'https://preview.redd.it/z6btu437zgi91.jpg?auto=webp&s=e633b3c45ce542ab88661d0e23db201d00a1b803','dateLimite' => '2025-12-04T00:00','saison' => '1/1','episode' => '1168/1'),
          array('user' => '1','nom' => 'Oppenheimer','categorie' => '8','lien' => 'https://nightflix{ext}/film/oppenheimer','description' => 'temps: 02:28:00','image' => 'https://summury.22web.org/banqueimage/img/amfs/films/oppenheimer.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Palette de couleur','categorie' => '5','lien' => 'https://www.palettedecouleur.net/','description' => 'répertorie les palettes armonieuses','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/palette.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'PapaDuStream','categorie' => '2','lien' => 'https://papa-adresse.lol/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/papdustream.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Percy Jackson','categorie' => '6','lien' => 'https://papadustream.doctor/cat-series/aventure-s/14585-percy-jackson-et-les-olympiens-ff0/1-saison/1-episode.html','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/percy-jackson-et-les-olympiens.png','dateLimite' => '2023-12-20','saison' => '1/1','episode' => '6/8'),
          array('user' => '1','nom' => 'PLR','categorie' => '1','lien' => 'https://sites.google.com/view/teamprl/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/plr.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'PLR','categorie' => '2','lien' => 'https://sites.google.com/view/prl-series/accueil?authuser=0','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/plr.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Prime Video','categorie' => '1','lien' => 'https://www.primevideo.com/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/prime_video.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'the promised neverland','categorie' => '14','lien' => 'https://anime-sama.fr/catalogue/the-promised-neverland/scan/vf/','description' => 'Dernier lu: 18','image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/the-promised-neverland.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Resize Pixel','categorie' => '5','lien' => 'https://www.resizepixel.com/fr','description' => 'Redimentionner les photos,gif,...','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/resize.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Re:Zero','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/rezero-kara-hajimeru-isekai-seikatsu/re-zero-kara-hajimeru-isekai-seikatsu-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/re-zero.jpg','dateLimite' => '2024-06-01T07:00','saison' => '1/3','episode' => '10/25'),
          array('user' => '1','nom' => 'Sakamoto Days','categorie' => '14','lien' => 'https://www.lelmanga.com/sakamoto-days-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/sakamoto-days.jpg','dateLimite' => '2023-04-02T15:30:00.000Z','saison' => '1/1','episode' => '17/0'),
          array('user' => '1','nom' => 'Saw X','categorie' => '8','lien' => 'https://nightflix{ext}/film/saw-x','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-10.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Saw II','categorie' => '8','lien' => 'https://nightflix{ext}/film/saw-2','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-2.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Saw III','categorie' => '8','lien' => 'https://nightflix{ext}/film/saw-3','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-3.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Saw IV','categorie' => '8','lien' => 'https://nightflix{ext}/film/saw-4','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-4.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Saw V','categorie' => '8','lien' => 'https://nightflix{ext}/film/saw-5','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-5.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Saucisse','categorie' => '8','lien' => 'https://nightflix{ext}/film/saw-6','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-6.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Zosette','categorie' => '8','lien' => 'https://nightflix{ext}/film/saw-3d-chapitre-final','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-7.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Jigsaw','categorie' => '8','lien' => 'https://nightflix{ext}/film/jigsaw','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-8.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Spiral: From the book of Saw','categorie' => '8','lien' => 'https://nightflix{ext}/film/spirale-l-heritage-de-saw','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/saw-9.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'scan vf','categorie' => '4','lien' => 'https://www.scan-vf.net/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/scan_vf.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Shaeishu','categorie' => '4','lien' => 'https://mangamoins.shaeishu.co/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/shaeishu.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Spy classroom','categorie' => '11','lien' => 'https://v6.voiranime.com/anime/spy-kyoushitsu/spy-kyoushitsu-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/spy-classroom.jpg','dateLimite' => '2024-01-13T13:30','saison' => '1/2','episode' => '16/12'),
          array('user' => '1','nom' => 'Spy X Family','categorie' => '11','lien' => 'https://anime-sama.fr/catalogue/spy-x-family/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/spy-x-family.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'steins; Gate','categorie' => '11','lien' => 'https://anime-sama.fr/catalogue/steins-gate','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/steins-gate.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Suno','categorie' => '5','lien' => 'https://suno.com/','description' => 'Créer de la musique','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/suno.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'sushiscan','categorie' => '4','lien' => 'https://sushiscan.top','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/sushiscan.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Sword Gai','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/sword-gai-the-animation/sword-gai-the-animation-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/sword-gai-the-animation.jpg','dateLimite' => '2025-04-25','saison' => '1/1','episode' => '14/12'),
          array('user' => '1','nom' => 'Terrifier 2','categorie' => '8','lien' => 'https://nightflix{ext}/film/terrifier-2','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/terrifier.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'The Kingdoms of ruin','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/hametsu-no-oukoku/the-kingdoms-of-ruin-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/the-kingdoms-of-ruin.jpg','dateLimite' => '2020-05-25T11:00:00.000Z','saison' => '1/1','episode' => '19/12'),
          array('user' => '1','nom' => 'the rising of the shield hero','categorie' => '11','lien' => 'https://v6.voiranime.com/anime/tate-no-yuusha-no-nariagari-3/tate-no-yuusha-no-nariagari-3-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/the-rising-of-the-shield-hero.jpg','dateLimite' => '2024-01-13T18:30:00.000Z','saison' => '3/3','episode' => '10/12'),
          array('user' => '1','nom' => 'The Witcher','categorie' => '6','lien' => 'https://www.netflix.com/search?q=the%20witcher&jbv=80189685','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/the-witcher.png','dateLimite' => '2023-12-20T12:30','saison' => '2/4','episode' => '10/8'),
          array('user' => '1','nom' => 'The Brilliant Healer’s New Life in the Shadows','categorie' => '11','lien' => 'https://v6.voiranime.com/anime/the-brilliant-healers-new-life-in-the-shadows/the-brilliant-healers-new-life-in-the-shadows-','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/TheBrilliantHealer.jpeg','dateLimite' => '2006-07-02T00:00','saison' => '1/1','episode' => '12/12'),
          array('user' => '1','nom' => 'The Walking Dead: Dead City','categorie' => '6','lien' => 'https://papadustream.doctor/cat-series/drame-s/13583-the-walking-dead-dead-city-700/1-saison/1-episode.html','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/The%20Walking%20Dead:%20Dead%20City.webp','dateLimite' => '2006-07-02','saison' => '2/2','episode' => '1/6'),
          array('user' => '1','nom' => 'The Walking Dead : The Ones Who Live','categorie' => '6','lien' => 'https://nightflix{ext}/serie/the-walking-dead-the-ones-who-live','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/The%20Walking%20Dead%20:%20The%20Ones%20Who%20Live.webp','dateLimite' => '2030-07-02T00:00','saison' => '2/2','episode' => '1/6'),
          array('user' => '1','nom' => 'Tome AI','categorie' => '5','lien' => 'https://tome.app/','description' => 'Générer des PowerPoint','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/tome_ai.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'To your Eternity','categorie' => '10','lien' => 'https://v6.voiranime.com/anime/fumetsu-no-anata-e-3/fumetsu-no-anata-e-3','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/to%20your%20eternity.jpg','dateLimite' => '2025-11-15T23:59','saison' => '3/3','episode' => '9/22'),
          array('user' => '1','nom' => 'The Promised Neverland','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/yakusoku-no-neverland/yakusoku-no-neverland-the-promised-neverland-','description' => '( 2 saisons )','image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/the-promised-neverland.jpg','dateLimite' => '2020-05-25T11:00:00.000Z','saison' => '1/1','episode' => '10/12'),
          array('user' => '1','nom' => 'Tokyo Revengers','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/tokyo-revengers/tokyo-revengers-nc-','description' => '3 saisons','image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/tokyo-revengers.jpg','dateLimite' => '2020-05-25T11:00:00.000Z','saison' => '1/1','episode' => '15/24'),
          array('user' => '1','nom' => 'Les 3 mousquetaires : Milady','categorie' => '8','lien' => 'https://nightflix{ext}/film/les-trois-mousquetaires-milady','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/films/troismousquetaires.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'TWD : Daryl Dixon','categorie' => '6','lien' => 'https://papadustream{ext}/cat-series/drame-s/14359-the-walking-dead-daryl-dixon-c1e/','description' => 'Lecteur : Filemoon, reste: 30:46','image' => 'https://summury.22web.org/banqueimage/img/amfs/series/twd-daryl.png','dateLimite' => '2020-10-17T13:00','saison' => '2/2','episode' => '4/6'),
          array('user' => '1','nom' => 'Under The Dome','categorie' => '6','lien' => 'https://papadustream{ext}/cat-series/drame-s/3163-under-the-dome-457/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/under_the_dome.png','dateLimite' => '2023-12-20T12:30','saison' => '2/3','episode' => '8/13'),
          array('user' => '1','nom' => 'Vikings','categorie' => '6','lien' => 'https://papadustream{ext}/cat-series/aventure-s/525-vikings-157/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/series/viking.jpeg','dateLimite' => '2006-07-02','saison' => '5/6','episode' => '12/20'),
          array('user' => '1','nom' => 'Villainess Level 99','categorie' => '10','lien' => 'https://v6.voiranime.com/anime/villainess-level-99/villainess-level-99-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/villainess-level-99.jpg','dateLimite' => '2025-10-04T00:00','saison' => '1/1','episode' => '10/12'),
          array('user' => '1','nom' => 'Voicemy AI','categorie' => '5','lien' => 'https://www.app.voicemy.ai/text-to-speech','description' => 'Générer des voix','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/voicemy_ai.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Voir Anime','categorie' => '3','lien' => 'https://voiranime.com/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/voir_anime.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Vostfree','categorie' => '3','lien' => 'https://vostfree.in/','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/vostfree.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'wiflix','categorie' => '1','lien' => 'https://flemmix.zip','description' => NULL,'image' => 'https://summury.22web.org/banqueimage/img/amfs/utiles/wiflix.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Wind breaker','categorie' => '10','lien' => 'https://v6.voiranime.com/anime/wind-breaker-2/wind-breaker-2-01-vostfr/','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/wind-breaker-manga.jpg','dateLimite' => '2025-05-15','saison' => '2/2','episode' => '8/12'),
          array('user' => '1','nom' => 'Writesonic','categorie' => '5','lien' => 'https://app.writesonic.com/fr/','description' => 'Écrire n\'importe quoi','image' => 'https://summury.22web.org/banqueimage/img/amfs/ai_tools/writesonic.png','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
          array('user' => '1','nom' => 'Yofukashi no Uta','categorie' => '11','lien' => 'https://v5.voiranime.com/anime/yofukashi-no-uta/yofukashi-no-uta-','description' => NULL,'image' => 'https://cdn.statically.io/gh/Anime-Sama/IMG/img/contenu/yofukashi-no-uta.jpg','dateLimite' => NULL,'saison' => '1/1','episode' => '1/1'),
        );

        foreach ($amfsRawData as $item) {
            
            // 1. CORRECTION ID UTILISATEUR: L'ID 35 (ou autre ID non défini) est réaffecté à 1 (utilisateur de test).
            $correctedIdUser = ($item['user'] == 35 || (int)$item['user'] > 3) ? 1 : (int)$item['user'];
            
            // 2. CORRECTION ID CATÉGORIE: Mappage de l'ancienne catégorie vers la nouvelle
            $oldCat = (string)$item['categorie']; 
            $correctedIdCategorie = $idMap[$oldCat] ?? 5; // Utilise Cat 5 (Outils) par défaut si non mappé.

            // 3. NETTOYAGE DE LA DATE
            $dateLimite = $item['dateLimite'];
            if (!empty($dateLimite)) {
                // Supprime 'T' et les millisecondes/Z pour correspondre au format DATETIME
                $dateLimite = str_replace(['T', '.000Z', 'Z'], ' ', $dateLimite);
                $dateLimite = trim($dateLimite);
            }

            // 4. Construction de l'enregistrement pour la nouvelle table `amfs`
            $data[] = [
                'idUser'      => $correctedIdUser,
                'idCategorie' => $item['categorie'], 
                'libelle'     => $item['nom'],
                'image'       => $item['image'],
                'lien'        => $item['lien'],
                'dateLimite'  => !empty($dateLimite) ? $dateLimite : null,
                'description' => $item['description'],
                'saison'      => $item['saison'] ?? 'N/A',
                'episode'     => $item['episode'] ?? 'N/A',
            ];
        }

        // Insertion des données en lot
        try {
            $this->db->table('amfs')->insertBatch($data);
            echo 'AmfsSeeder : ' . count($data) . " enregistrements importés et corrigés insérés avec succès.\n";
        } catch (\Exception $e) {
            echo 'AmfsSeeder Error: ' . $e->getMessage() . "\n";
        }
    }
}